[package]
name = "basalto-communication"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
libloading = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
basalto-common = { path = "../basalto-common" }

[features]
default = []
gpu_aware = [] 