[package]
name = "basalto-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
basalto-common = { path = "../basalto-common" }
basalto-core = { path = "../basalto-core" }
basalto-target-nvidia = { path = "../basalto-target-nvidia" }
basalto-gems = { path = "../basalto-gems" }
tokio = { workspace = true }
serde = { workspace = true }
bincode = "1.3"
dirs = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module"] }